# This is an example foreman config file.
# All fields are optional unless marked REQUIRED.
# Copy this file before making changes `cp example.foreman.toml foreman.toml`

[core]
# URL of the control server - REQUIRED
url = "http://localhost:8888/job"

# API token for authentication with control server - REQUIRED
token = "YOUR_TOKEN_HERE"

# Hostname containers will use to access the agent's API - REQUIRED
hostname = "YOUR_HOSTNAME_HERE"

# Port on which to expose foreman
# port = 3000

# Additional hosts to add to containers e.g. `extra_hosts = ["host.docker.internal:host-gateway"]`
# extra_hosts = []

# How frequently to poll the control server for jobs
# poll_frequency = 5000

# How long to wait for a response from the control server
# poll_timeout = 30000


[docker]
# Docker deamon endpoint
# url = 'unix:///var/run/docker.sock'

# Start port for container mapping
# start_port = 49152

# End port for container mapping
# end_port = 65535

# How long to wait for a container to report healthy status
# container_timeout = 10000
