name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write  # For creating releases

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating release for ${{ env.GITHUB_REF_NAME }}"
        gh release create --generate-notes ${{ env.GITHUB_REF_NAME }} target/release/foreman